language: python

python:
- "2.7"

install:
- pip install coveralls
- pip install coverage
- pip install -r requirements.txt

script: 
- coverage run --source=identity --module unittest discover --verbose
